### ISSUE TITLE
no implicit conversion of nil into Hash

### ISSUE THREAD

**Issue by Godweed** [spree-contrib/spree_mail_settings#43]
When  I am trying to send test email I am getting no implicit conversion of nil into Hash error in spree version 3.3 with rails 5.1.4

**Comment by Godweed** [comment]
F, [2017-10-13T20:33:20.965934 #3617] FATAL -- : [77a3f91f-8cac-4d73-9884-aa2f77e3fbc6]   
F, [2017-10-13T20:33:20.965994 #3617] FATAL -- : [77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] TypeError (no implicit conversion of nil into Hash):
F, [2017-10-13T20:33:20.966040 #3617] FATAL -- : [77a3f91f-8cac-4d73-9884-aa2f77e3fbc6]   
F, [2017-10-13T20:33:20.966105 #3617] FATAL -- : [77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] mail (2.6.6) lib/mail/network/delivery_methods/smtp.rb:91:in `merge!'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] mail (2.6.6) lib/mail/network/delivery_methods/smtp.rb:91:in `initialize'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/spree_mail_settings-78079efe4463/lib/spree/core/mail_method.rb:12:in `new'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/spree_mail_settings-78079efe4463/lib/spree/core/mail_method.rb:12:in `mailer'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/spree_mail_settings-78079efe4463/lib/spree/core/mail_method.rb:8:in `deliver!'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] mail (2.6.6) lib/mail/message.rb:2149:in `do_delivery'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] mail (2.6.6) lib/mail/message.rb:237:in `block in deliver'
[77a3f91f-8cac-4d73-9884-aa2f77e3fbc6] actionmailer (5.1.4) lib/action_mailer/base.rb:558:in `block in deliver_mail'

**Comment by softr8** [comment]
I was able to find the root cause, I think....

it is due this change: https://github.com/spree-contrib/spree_mail_settings/commit/9582282420a0b011af81c4dfc9c14868d2124881 if the connection is not secure, it just returns nil instead of settings object
